
package wsimport.lib.amadeus.pnr.issue;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsIssueTicketSoap", targetNamespace = "http://traveltalk.com/wsIssueTicket")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsIssueTicketSoap {


    /**
     * Process Issue Ticket Messages Request.
     * 
     * @param ttIssueTicketRQ
     * @return
     *     returns com.traveltalk.wsissueticket.TTIssueTicketRS
     */
    @WebMethod(action = "http://traveltalk.com/wsIssueTicket/wmIssueTicket")
    @WebResult(name = "TT_IssueTicketRS", targetNamespace = "http://traveltalk.com/wsIssueTicket")
    @RequestWrapper(localName = "wmIssueTicket", targetNamespace = "http://traveltalk.com/wsIssueTicket", className = "com.traveltalk.wsissueticket.WmIssueTicket")
    @ResponseWrapper(localName = "wmIssueTicketResponse", targetNamespace = "http://traveltalk.com/wsIssueTicket", className = "com.traveltalk.wsissueticket.WmIssueTicketResponse")
    public TTIssueTicketRS wmIssueTicket(
            @WebParam(name = "TT_IssueTicketRQ", targetNamespace = "http://traveltalk.com/wsIssueTicket")
                    TTIssueTicketRQ ttIssueTicketRQ);

    /**
     * Process Issue Ticket Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsIssueTicket/wmIssueTicketXml")
    @WebResult(name = "wmIssueTicketXmlResult", targetNamespace = "http://traveltalk.com/wsIssueTicket")
    @RequestWrapper(localName = "wmIssueTicketXml", targetNamespace = "http://traveltalk.com/wsIssueTicket", className = "com.traveltalk.wsissueticket.WmIssueTicketXml")
    @ResponseWrapper(localName = "wmIssueTicketXmlResponse", targetNamespace = "http://traveltalk.com/wsIssueTicket", className = "com.traveltalk.wsissueticket.WmIssueTicketXmlResponse")
    public String wmIssueTicketXml(
            @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsIssueTicket")
                    String xmlRequest);

}
