
package wsimport.lib.amadeus.pnr.issue;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Issue Ticket Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsIssueTicket", targetNamespace = "http://traveltalk.com/wsIssueTicket", wsdlLocation = "http://amadeusws.tripxml.com/TripXML/wsIssueTicket.asmx?WSDL")
public class WsIssueTicket
    extends Service
{

    private final static URL WSISSUETICKET_WSDL_LOCATION;
    private final static WebServiceException WSISSUETICKET_EXCEPTION;
    private final static QName WSISSUETICKET_QNAME = new QName("http://traveltalk.com/wsIssueTicket", "wsIssueTicket");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://amadeusws.tripxml.com/TripXML/wsIssueTicket.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSISSUETICKET_WSDL_LOCATION = url;
        WSISSUETICKET_EXCEPTION = e;
    }

    public WsIssueTicket() {
        super(__getWsdlLocation(), WSISSUETICKET_QNAME);
    }

    public WsIssueTicket(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSISSUETICKET_QNAME, features);
    }

    public WsIssueTicket(URL wsdlLocation) {
        super(wsdlLocation, WSISSUETICKET_QNAME);
    }

    public WsIssueTicket(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSISSUETICKET_QNAME, features);
    }

    public WsIssueTicket(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsIssueTicket(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsIssueTicketSoap
     */
    @WebEndpoint(name = "wsIssueTicketSoap")
    public WsIssueTicketSoap getWsIssueTicketSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsIssueTicket", "wsIssueTicketSoap"), WsIssueTicketSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <itemTypes>features</itemTypes> parameter will have their default values.
     * @return
     *     returns WsIssueTicketSoap
     */
    @WebEndpoint(name = "wsIssueTicketSoap")
    public WsIssueTicketSoap getWsIssueTicketSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsIssueTicket", "wsIssueTicketSoap"), WsIssueTicketSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSISSUETICKET_EXCEPTION!= null) {
            throw WSISSUETICKET_EXCEPTION;
        }
        return WSISSUETICKET_WSDL_LOCATION;
    }

}
