
package wsimport.lib.amadeus.wsairrules;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsAirRulesSoap", targetNamespace = "http://traveltalk.com/wsAirRules")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAirRulesSoap {


    /**
     * Process Air Rules Messages Request.
     * 
     * @param otaAirRulesRQ
     * @return
     *     returns wsimport.lib.amadeus.wsairrules.OTAAirRulesRS
     */
    @WebMethod(action = "http://traveltalk.com/wsAirRules/wmAirRules")
    @WebResult(name = "OTA_AirRulesRS", targetNamespace = "http://traveltalk.com/wsAirRules")
    @RequestWrapper(localName = "wmAirRules", targetNamespace = "http://traveltalk.com/wsAirRules", className = "wsimport.lib.amadeus.wsairrules.WmAirRules")
    @ResponseWrapper(localName = "wmAirRulesResponse", targetNamespace = "http://traveltalk.com/wsAirRules", className = "wsimport.lib.amadeus.wsairrules.WmAirRulesResponse")
    public OTAAirRulesRS wmAirRules(
        @WebParam(name = "OTA_AirRulesRQ", targetNamespace = "http://traveltalk.com/wsAirRules")
        OTAAirRulesRQ otaAirRulesRQ);

    /**
     * Process Air Rules Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsAirRules/wmAirRulesXml")
    @WebResult(name = "wmAirRulesXmlResult", targetNamespace = "http://traveltalk.com/wsAirRules")
    @RequestWrapper(localName = "wmAirRulesXml", targetNamespace = "http://traveltalk.com/wsAirRules", className = "wsimport.lib.amadeus.wsairrules.WmAirRulesXml")
    @ResponseWrapper(localName = "wmAirRulesXmlResponse", targetNamespace = "http://traveltalk.com/wsAirRules", className = "wsimport.lib.amadeus.wsairrules.WmAirRulesXmlResponse")
    public String wmAirRulesXml(
        @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsAirRules")
        String xmlRequest);

}
