
package wsimport.lib.amadeus.travelbuild;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsTravelBuild_v03Soap", targetNamespace = "http://traveltalk.com/wsTravelBuild")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsTravelBuildV03Soap {


    /**
     * Process Travel Build Messages Request.
     * 
     * @param otaTravelItineraryRQ
     * @return
     *     returns travelbuild.OTATravelItineraryRS
     */
    @WebMethod(action = "http://traveltalk.com/wsTravelBuild/wmTravelBuild")
    @WebResult(name = "OTA_TravelItineraryRS", targetNamespace = "http://traveltalk.com/wsTravelBuild")
    @RequestWrapper(localName = "wmTravelBuild", targetNamespace = "http://traveltalk.com/wsTravelBuild", className = "travelbuild.WmTravelBuild")
    @ResponseWrapper(localName = "wmTravelBuildResponse", targetNamespace = "http://traveltalk.com/wsTravelBuild", className = "travelbuild.WmTravelBuildResponse")
    public OTATravelItineraryRS wmTravelBuild(
            @WebParam(name = "OTA_TravelItineraryRQ", targetNamespace = "http://traveltalk.com/wsTravelBuild")
                    OTATravelItineraryRQ otaTravelItineraryRQ);

    /**
     * Process Travel Build Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsTravelBuild/wmTravelBuildXml")
    @WebResult(name = "wmTravelBuildXmlResult", targetNamespace = "http://traveltalk.com/wsTravelBuild")
    @RequestWrapper(localName = "wmTravelBuildXml", targetNamespace = "http://traveltalk.com/wsTravelBuild", className = "travelbuild.WmTravelBuildXml")
    @ResponseWrapper(localName = "wmTravelBuildXmlResponse", targetNamespace = "http://traveltalk.com/wsTravelBuild", className = "travelbuild.WmTravelBuildXmlResponse")
    public String wmTravelBuildXml(
            @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsTravelBuild")
                    String xmlRequest);

}
