
package wsimport.lib.amadeus.airfliforq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Air Flight Info Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsAirFlifo", targetNamespace = "http://traveltalk.com/wsAirFlifo", wsdlLocation = "http://amadeusws.tripxml.com/TripXML/wsAirFlifo.asmx?WSDL")
public class WsAirFlifo
    extends Service
{

    private final static URL WSAIRFLIFO_WSDL_LOCATION;
    private final static WebServiceException WSAIRFLIFO_EXCEPTION;
    private final static QName WSAIRFLIFO_QNAME = new QName("http://traveltalk.com/wsAirFlifo", "wsAirFlifo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://amadeusws.tripxml.com/TripXML/wsAirFlifo.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAIRFLIFO_WSDL_LOCATION = url;
        WSAIRFLIFO_EXCEPTION = e;
    }

    public WsAirFlifo() {
        super(__getWsdlLocation(), WSAIRFLIFO_QNAME);
    }

    public WsAirFlifo(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAIRFLIFO_QNAME, features);
    }

    public WsAirFlifo(URL wsdlLocation) {
        super(wsdlLocation, WSAIRFLIFO_QNAME);
    }

    public WsAirFlifo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAIRFLIFO_QNAME, features);
    }

    public WsAirFlifo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAirFlifo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsAirFlifoSoap
     */
    @WebEndpoint(name = "wsAirFlifoSoap")
    public WsAirFlifoSoap getWsAirFlifoSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsAirFlifo", "wsAirFlifoSoap"), WsAirFlifoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <itemTypes>features</itemTypes> parameter will have their default values.
     * @return
     *     returns WsAirFlifoSoap
     */
    @WebEndpoint(name = "wsAirFlifoSoap")
    public WsAirFlifoSoap getWsAirFlifoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsAirFlifo", "wsAirFlifoSoap"), WsAirFlifoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAIRFLIFO_EXCEPTION!= null) {
            throw WSAIRFLIFO_EXCEPTION;
        }
        return WSAIRFLIFO_WSDL_LOCATION;
    }

}
