
package wsimport.lib.amadeus.airfliforq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsAirFlifoSoap", targetNamespace = "http://traveltalk.com/wsAirFlifo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAirFlifoSoap {


    /**
     * Process Air Flight Info Messages Request.
     * 
     * @param otaAirFlifoRQ
     * @return
     *     returns soap.client.airfliforq.OTAAirFlifoRS
     */
    @WebMethod(action = "http://traveltalk.com/wsAirFlifo/wmAirFlifo")
    @WebResult(name = "OTA_AirFlifoRS", targetNamespace = "http://traveltalk.com/wsAirFlifo")
    @RequestWrapper(localName = "wmAirFlifo", targetNamespace = "http://traveltalk.com/wsAirFlifo", className = "soap.client.airfliforq.WmAirFlifo")
    @ResponseWrapper(localName = "wmAirFlifoResponse", targetNamespace = "http://traveltalk.com/wsAirFlifo", className = "soap.client.airfliforq.WmAirFlifoResponse")
    public OTAAirFlifoRS wmAirFlifo(
            @WebParam(name = "OTA_AirFlifoRQ", targetNamespace = "http://traveltalk.com/wsAirFlifo")
                    OTAAirFlifoRQ otaAirFlifoRQ);

    /**
     * Process Air Flight Info Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsAirFlifo/wmAirFlifoXml")
    @WebResult(name = "wmAirFlifoXmlResult", targetNamespace = "http://traveltalk.com/wsAirFlifo")
    @RequestWrapper(localName = "wmAirFlifoXml", targetNamespace = "http://traveltalk.com/wsAirFlifo", className = "soap.client.airfliforq.WmAirFlifoXml")
    @ResponseWrapper(localName = "wmAirFlifoXmlResponse", targetNamespace = "http://traveltalk.com/wsAirFlifo", className = "soap.client.airfliforq.WmAirFlifoXmlResponse")
    public String wmAirFlifoXml(
            @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsAirFlifo")
                    String xmlRequest);

}
