
package wsimport.lib.sabre.airavail;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OTA_AirAvailPortType", targetNamespace = "https://webservices.service.sabre.com/websvc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OTAAirAvailPortType {

    /**
     * 
     * @param header2
     * @param header
     * @param body
     * @return
     *     returns client.OTAAirAvailRS
     */
    @WebMethod(operationName = "OTA_AirAvailRQ", action = "OTA_AirAvailLLSRQ")
    @WebResult(name = "OTA_AirAvailRS", targetNamespace = "http://webservices.service.sabre.com/sabreXML/2011/10", partName = "body")
    public OTAAirAvailRS otaAirAvailRQ(
            @WebParam(name = "MessageHeader", targetNamespace = "http://www.ebxml.org/namespaces/messageHeader", header = true, mode = WebParam.Mode.INOUT, partName = "header")
                    Holder<MessageHeader> header,
            @WebParam(name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", header = true, mode = WebParam.Mode.INOUT, partName = "header2")
                    Holder<Security2> header2,
            @WebParam(name = "OTA_AirAvailRQ", targetNamespace = "http://webservices.service.sabre.com/sabreXML/2011/10", partName = "body")
                    OTAAirAvailRQ body);

}
