
package wsimport.lib.amadeus.lowfareplus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Low Fare Plus Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsLowFarePlus", targetNamespace = "http://traveltalk.com/wsLowFarePlus", wsdlLocation = "http://amadeusws.tripxml.com/TripXML/wsLowFarePlus.asmx?WSDL")
public class WsLowFarePlus
    extends Service
{

    private final static URL WSLOWFAREPLUS_WSDL_LOCATION;
    private final static WebServiceException WSLOWFAREPLUS_EXCEPTION;
    private final static QName WSLOWFAREPLUS_QNAME = new QName("http://traveltalk.com/wsLowFarePlus", "wsLowFarePlus");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://amadeusws.tripxml.com/TripXML/wsLowFarePlus.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSLOWFAREPLUS_WSDL_LOCATION = url;
        WSLOWFAREPLUS_EXCEPTION = e;
    }

    public WsLowFarePlus() {
        super(__getWsdlLocation(), WSLOWFAREPLUS_QNAME);
    }

    public WsLowFarePlus(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSLOWFAREPLUS_QNAME, features);
    }

    public WsLowFarePlus(URL wsdlLocation) {
        super(wsdlLocation, WSLOWFAREPLUS_QNAME);
    }

    public WsLowFarePlus(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSLOWFAREPLUS_QNAME, features);
    }

    public WsLowFarePlus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsLowFarePlus(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsLowFarePlusSoap
     */
    @WebEndpoint(name = "wsLowFarePlusSoap")
    public WsLowFarePlusSoap getWsLowFarePlusSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsLowFarePlus", "wsLowFarePlusSoap"), WsLowFarePlusSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <itemTypes>features</itemTypes> parameter will have their default values.
     * @return
     *     returns WsLowFarePlusSoap
     */
    @WebEndpoint(name = "wsLowFarePlusSoap")
    public WsLowFarePlusSoap getWsLowFarePlusSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsLowFarePlus", "wsLowFarePlusSoap"), WsLowFarePlusSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSLOWFAREPLUS_EXCEPTION!= null) {
            throw WSLOWFAREPLUS_EXCEPTION;
        }
        return WSLOWFAREPLUS_WSDL_LOCATION;
    }

}
