
package wsimport.lib.amadeus.wsairseatmap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Air Seat Map Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsAirSeatMap", targetNamespace = "http://traveltalk.com/wsAirSeatMap", wsdlLocation = "http://amadeusws.tripxml.com/TripXML/wsAirSeatMap.asmx?WSDL")
public class WsAirSeatMap
    extends Service
{

    private final static URL WSAIRSEATMAP_WSDL_LOCATION;
    private final static WebServiceException WSAIRSEATMAP_EXCEPTION;
    private final static QName WSAIRSEATMAP_QNAME = new QName("http://traveltalk.com/wsAirSeatMap", "wsAirSeatMap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://amadeusws.tripxml.com/TripXML/wsAirSeatMap.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAIRSEATMAP_WSDL_LOCATION = url;
        WSAIRSEATMAP_EXCEPTION = e;
    }

    public WsAirSeatMap() {
        super(__getWsdlLocation(), WSAIRSEATMAP_QNAME);
    }

    public WsAirSeatMap(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAIRSEATMAP_QNAME, features);
    }

    public WsAirSeatMap(URL wsdlLocation) {
        super(wsdlLocation, WSAIRSEATMAP_QNAME);
    }

    public WsAirSeatMap(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAIRSEATMAP_QNAME, features);
    }

    public WsAirSeatMap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAirSeatMap(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsAirSeatMapSoap
     */
    @WebEndpoint(name = "wsAirSeatMapSoap")
    public WsAirSeatMapSoap getWsAirSeatMapSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsAirSeatMap", "wsAirSeatMapSoap"), WsAirSeatMapSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsAirSeatMapSoap
     */
    @WebEndpoint(name = "wsAirSeatMapSoap")
    public WsAirSeatMapSoap getWsAirSeatMapSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsAirSeatMap", "wsAirSeatMapSoap"), WsAirSeatMapSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAIRSEATMAP_EXCEPTION!= null) {
            throw WSAIRSEATMAP_EXCEPTION;
        }
        return WSAIRSEATMAP_WSDL_LOCATION;
    }

}
