
package wsimport.lib.amadeus.wsairseatmap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsAirSeatMapSoap", targetNamespace = "http://traveltalk.com/wsAirSeatMap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAirSeatMapSoap {


    /**
     * Process Air Seat Map Messages Request.
     * 
     * @param otaAirSeatMapRQ
     * @return
     *     returns wsimport.lib.amadeus.wsairseatmap.OTAAirSeatMapRS
     */
    @WebMethod(action = "http://traveltalk.com/wsAirSeatMap/wmAirSeatMap")
    @WebResult(name = "OTA_AirSeatMapRS", targetNamespace = "http://traveltalk.com/wsAirSeatMap")
    @RequestWrapper(localName = "wmAirSeatMap", targetNamespace = "http://traveltalk.com/wsAirSeatMap", className = "wsimport.lib.amadeus.wsairseatmap.WmAirSeatMap")
    @ResponseWrapper(localName = "wmAirSeatMapResponse", targetNamespace = "http://traveltalk.com/wsAirSeatMap", className = "wsimport.lib.amadeus.wsairseatmap.WmAirSeatMapResponse")
    public OTAAirSeatMapRS wmAirSeatMap(
        @WebParam(name = "OTA_AirSeatMapRQ", targetNamespace = "http://traveltalk.com/wsAirSeatMap")
        OTAAirSeatMapRQ otaAirSeatMapRQ);

    /**
     * Process Air Seat Map Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsAirSeatMap/wmAirSeatMapXml")
    @WebResult(name = "wmAirSeatMapXmlResult", targetNamespace = "http://traveltalk.com/wsAirSeatMap")
    @RequestWrapper(localName = "wmAirSeatMapXml", targetNamespace = "http://traveltalk.com/wsAirSeatMap", className = "wsimport.lib.amadeus.wsairseatmap.WmAirSeatMapXml")
    @ResponseWrapper(localName = "wmAirSeatMapXmlResponse", targetNamespace = "http://traveltalk.com/wsAirSeatMap", className = "wsimport.lib.amadeus.wsairseatmap.WmAirSeatMapXmlResponse")
    public String wmAirSeatMapXml(
        @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsAirSeatMap")
        String xmlRequest);

}
