
package wsimport.lib.sabre.passengerdetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PassengerDetailsService", targetNamespace = "https://webservices.sabre.com/websvc", wsdlLocation = "http://webservices.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/PassengerDetails3.2.0RQ.wsdl")
public class PassengerDetailsService
    extends Service
{

    private final static URL PASSENGERDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PASSENGERDETAILSSERVICE_EXCEPTION;
    private final static QName PASSENGERDETAILSSERVICE_QNAME = new QName("https://webservices.sabre.com/websvc", "PassengerDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/PassengerDetails3.2.0RQ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSENGERDETAILSSERVICE_WSDL_LOCATION = url;
        PASSENGERDETAILSSERVICE_EXCEPTION = e;
    }

    public PassengerDetailsService() {
        super(__getWsdlLocation(), PASSENGERDETAILSSERVICE_QNAME);
    }

    public PassengerDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PASSENGERDETAILSSERVICE_QNAME, features);
    }

    public PassengerDetailsService(URL wsdlLocation) {
        super(wsdlLocation, PASSENGERDETAILSSERVICE_QNAME);
    }

    public PassengerDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PASSENGERDETAILSSERVICE_QNAME, features);
    }

    public PassengerDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PassengerDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PassengerDetailsPortType
     */
    @WebEndpoint(name = "PassengerDetailsPortType")
    public PassengerDetailsPortType getPassengerDetailsPortType() {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "PassengerDetailsPortType"), PassengerDetailsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <itemTypes>features</itemTypes> parameter will have their default values.
     * @return
     *     returns PassengerDetailsPortType
     */
    @WebEndpoint(name = "PassengerDetailsPortType")
    public PassengerDetailsPortType getPassengerDetailsPortType(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "PassengerDetailsPortType"), PassengerDetailsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSENGERDETAILSSERVICE_EXCEPTION!= null) {
            throw PASSENGERDETAILSSERVICE_EXCEPTION;
        }
        return PASSENGERDETAILSSERVICE_WSDL_LOCATION;
    }

}
