
package wsimport.lib.amadeus.wshotelavail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsHotelAvailSoap", targetNamespace = "http://traveltalk.com/wsHotelAvail")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsHotelAvailSoap {


    /**
     * Process Hotel Availability Messages Request.
     * 
     * @param otaHotelAvailRQ
     * @return
     *     returns wsimport.lib.amadeus.wshotelavail.OTAHotelAvailRS
     */
    @WebMethod(action = "http://traveltalk.com/wsHotelAvail/wmHotelAvail")
    @WebResult(name = "OTA_HotelAvailRS", targetNamespace = "http://traveltalk.com/wsHotelAvail")
    @RequestWrapper(localName = "wmHotelAvail", targetNamespace = "http://traveltalk.com/wsHotelAvail", className = "wsimport.lib.amadeus.wshotelavail.WmHotelAvail")
    @ResponseWrapper(localName = "wmHotelAvailResponse", targetNamespace = "http://traveltalk.com/wsHotelAvail", className = "wsimport.lib.amadeus.wshotelavail.WmHotelAvailResponse")
    public OTAHotelAvailRS wmHotelAvail(
        @WebParam(name = "OTA_HotelAvailRQ", targetNamespace = "http://traveltalk.com/wsHotelAvail")
        OTAHotelAvailRQ otaHotelAvailRQ);

    /**
     * Process Hotel Availability Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsHotelAvail/wmHotelAvailXml")
    @WebResult(name = "wmHotelAvailXmlResult", targetNamespace = "http://traveltalk.com/wsHotelAvail")
    @RequestWrapper(localName = "wmHotelAvailXml", targetNamespace = "http://traveltalk.com/wsHotelAvail", className = "wsimport.lib.amadeus.wshotelavail.WmHotelAvailXml")
    @ResponseWrapper(localName = "wmHotelAvailXmlResponse", targetNamespace = "http://traveltalk.com/wsHotelAvail", className = "wsimport.lib.amadeus.wshotelavail.WmHotelAvailXmlResponse")
    public String wmHotelAvailXml(
        @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsHotelAvail")
        String xmlRequest);

}
