
package wsimport.lib.amadeus.wshotelavail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Hotel Availability Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsHotelAvail", targetNamespace = "http://traveltalk.com/wsHotelAvail", wsdlLocation = "http://www.TripXML.com/TripXML/wsHotelAvail.asmx?wsdl")
public class WsHotelAvail
    extends Service
{

    private final static URL WSHOTELAVAIL_WSDL_LOCATION;
    private final static WebServiceException WSHOTELAVAIL_EXCEPTION;
    private final static QName WSHOTELAVAIL_QNAME = new QName("http://traveltalk.com/wsHotelAvail", "wsHotelAvail");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.TripXML.com/TripXML/wsHotelAvail.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSHOTELAVAIL_WSDL_LOCATION = url;
        WSHOTELAVAIL_EXCEPTION = e;
    }

    public WsHotelAvail() {
        super(__getWsdlLocation(), WSHOTELAVAIL_QNAME);
    }

    public WsHotelAvail(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSHOTELAVAIL_QNAME, features);
    }

    public WsHotelAvail(URL wsdlLocation) {
        super(wsdlLocation, WSHOTELAVAIL_QNAME);
    }

    public WsHotelAvail(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSHOTELAVAIL_QNAME, features);
    }

    public WsHotelAvail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsHotelAvail(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsHotelAvailSoap
     */
    @WebEndpoint(name = "wsHotelAvailSoap")
    public WsHotelAvailSoap getWsHotelAvailSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsHotelAvail", "wsHotelAvailSoap"), WsHotelAvailSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsHotelAvailSoap
     */
    @WebEndpoint(name = "wsHotelAvailSoap")
    public WsHotelAvailSoap getWsHotelAvailSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsHotelAvail", "wsHotelAvailSoap"), WsHotelAvailSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSHOTELAVAIL_EXCEPTION!= null) {
            throw WSHOTELAVAIL_EXCEPTION;
        }
        return WSHOTELAVAIL_WSDL_LOCATION;
    }

}
