
package wsimport.lib.epower;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EpowerServiceSoap", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EpowerServiceSoap {


    /**
     * 
     * @param otaPingRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.PingResponse.OTAPingRS
     */
    @WebMethod(operationName = "Ping", action = "http://epowerv5.amadeus.com.tr/WS/Ping")
    @WebResult(name = "OTA_PingRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.PingResponse")
    public wsimport.lib.epower.PingResponse.OTAPingRS ping(
        @WebParam(name = "OTA_PingRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.Ping.OTAPingRQ otaPingRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SignOut", action = "http://epowerv5.amadeus.com.tr/WS/SignOut")
    @WebResult(name = "SignOutResult", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SignOut", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SignOut")
    @ResponseWrapper(localName = "SignOutResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SignOutResponse")
    public boolean signOut();

    /**
     * 
     * @param otaCurrencyConversionRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTACurrencyConversionRS
     */
    @WebMethod(operationName = "CurrencyConversion", action = "http://epowerv5.amadeus.com.tr/WS/CurrencyConversion")
    @WebResult(name = "OTA_CurrencyConversionRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "CurrencyConversion", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CurrencyConversion")
    @ResponseWrapper(localName = "CurrencyConversionResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CurrencyConversionResponse")
    public OTACurrencyConversionRS currencyConversion(
        @WebParam(name = "OTA_CurrencyConversionRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTACurrencyConversionRQ otaCurrencyConversionRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader
        );

    /**
     * 
     * @param otaCancelRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.CancelResponse.OTACancelRS
     */
    @WebMethod(operationName = "Cancel", action = "http://epowerv5.amadeus.com.tr/WS/Cancel")
    @WebResult(name = "OTA_CancelRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "Cancel", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.Cancel")
    @ResponseWrapper(localName = "CancelResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CancelResponse")
    public wsimport.lib.epower.CancelResponse.OTACancelRS cancel(
        @WebParam(name = "OTA_CancelRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.Cancel.OTACancelRQ otaCancelRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param queueRQ
     * @return
     *     returns wsimport.lib.epower.QueueRS
     */
    @WebMethod(operationName = "Queue", action = "http://epowerv5.amadeus.com.tr/WS/Queue")
    @WebResult(name = "QueueRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "Queue", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.Queue")
    @ResponseWrapper(localName = "QueueResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.QueueResponse")
    public QueueRS queue(
        @WebParam(name = "QueueRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        QueueRQ queueRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaAirLowFareSearchRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.SearchFlightResponse.OTAAirLowFareSearchRS
     */
    @WebMethod(operationName = "SearchFlight", action = "http://epowerv5.amadeus.com.tr/WS/SearchFlight")
    @WebResult(name = "OTA_AirLowFareSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchFlight", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlight")
    @ResponseWrapper(localName = "SearchFlightResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlightResponse")
    public wsimport.lib.epower.SearchFlightResponse.OTAAirLowFareSearchRS searchFlight(
        @WebParam(name = "OTA_AirLowFareSearchRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.SearchFlight.OTAAirLowFareSearchRQ otaAirLowFareSearchRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader
    );

    /**
     * 
     * @param serviceFeeInfoRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.ServiceFeeInfoRS
     */
    @WebMethod(operationName = "GetServiceFee", action = "http://epowerv5.amadeus.com.tr/WS/GetServiceFee")
    @WebResult(name = "ServiceFeeInfoRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetServiceFee", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetServiceFee")
    @ResponseWrapper(localName = "GetServiceFeeResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetServiceFeeResponse")
    public ServiceFeeInfoRS getServiceFee(
        @WebParam(name = "ServiceFeeInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        ServiceFeeInfoRQ serviceFeeInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader
    );

    /**
     * 
     * @param baggageInfoRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.BaggageInfoRS
     */
    @WebMethod(operationName = "GetBaggageInfo", action = "http://epowerv5.amadeus.com.tr/WS/GetBaggageInfo")
    @WebResult(name = "BaggageInfoRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetBaggageInfo", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetBaggageInfo")
    @ResponseWrapper(localName = "GetBaggageInfoResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetBaggageInfoResponse")
    public BaggageInfoRS getBaggageInfo(
        @WebParam(name = "BaggageInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        BaggageInfoRQ baggageInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param ancillaryInfoRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.AncillaryInfoRS
     */
    @WebMethod(operationName = "GetAncillaryInfo", action = "http://epowerv5.amadeus.com.tr/WS/GetAncillaryInfo")
    @WebResult(name = "AncillaryInfoRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetAncillaryInfo", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetAncillaryInfo")
    @ResponseWrapper(localName = "GetAncillaryInfoResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetAncillaryInfoResponse")
    public AncillaryInfoRS getAncillaryInfo(
        @WebParam(name = "AncillaryInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        AncillaryInfoRQ ancillaryInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param flightOptionRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetCompatibleLowestFaresForSunExpressResponse.OTAAirLowFareSearchRS
     */
    @WebMethod(operationName = "GetCompatibleLowestFaresForSunExpress", action = "http://epowerv5.amadeus.com.tr/WS/GetCompatibleLowestFaresForSunExpress")
    @WebResult(name = "OTA_AirLowFareSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetCompatibleLowestFaresForSunExpress", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCompatibleLowestFaresForSunExpress")
    @ResponseWrapper(localName = "GetCompatibleLowestFaresForSunExpressResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCompatibleLowestFaresForSunExpressResponse")
    public wsimport.lib.epower.GetCompatibleLowestFaresForSunExpressResponse.OTAAirLowFareSearchRS getCompatibleLowestFaresForSunExpress(
        @WebParam(name = "FlightOptionRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        FlightOptionRQ flightOptionRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param serviceFeeInfoRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.ServiceFeeInfoRS
     */
    @WebMethod(operationName = "GetServiceFeeV2", action = "http://epowerv5.amadeus.com.tr/WS/GetServiceFeeV2")
    @WebResult(name = "ServiceFeeInfoRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetServiceFeeV2", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetServiceFeeV2")
    @ResponseWrapper(localName = "GetServiceFeeV2Response", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetServiceFeeV2Response")
    public ServiceFeeInfoRS getServiceFeeV2(
        @WebParam(name = "ServiceFeeInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        ServiceFeeInfoRQ serviceFeeInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param priceInfoRQ
     * @return
     *     returns wsimport.lib.epower.GetPriceResponse.OTAAirLowFareSearchRS
     */
    @WebMethod(operationName = "GetPrice", action = "http://epowerv5.amadeus.com.tr/WS/GetPrice")
    @WebResult(name = "OTA_AirLowFareSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetPrice", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetPrice")
    @ResponseWrapper(localName = "GetPriceResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetPriceResponse")
    public wsimport.lib.epower.GetPriceResponse.OTAAirLowFareSearchRS getPrice(
        @WebParam(name = "PriceInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        PriceInfoRQ priceInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param genericSoapHeader
     * @param requiredParametersRQ
     * @return
     *     returns wsimport.lib.epower.GetRequiredParametersForLCCResponse.RequiredParametersRS
     */
    @WebMethod(operationName = "GetRequiredParametersForLCC", action = "http://epowerv5.amadeus.com.tr/WS/GetRequiredParametersForLCC")
    @WebResult(name = "RequiredParametersRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetRequiredParametersForLCC", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetRequiredParametersForLCC")
    @ResponseWrapper(localName = "GetRequiredParametersForLCCResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetRequiredParametersForLCCResponse")
    public wsimport.lib.epower.GetRequiredParametersForLCCResponse.RequiredParametersRS getRequiredParametersForLCC(
        @WebParam(name = "RequiredParametersRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        RequiredParametersRQ requiredParametersRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetNextFlightResultsResponse.OTAAirLowFareSearchRS
     */
    @WebMethod(operationName = "GetNextFlightResults", action = "http://epowerv5.amadeus.com.tr/WS/GetNextFlightResults")
    @WebResult(name = "OTA_AirLowFareSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetNextFlightResults", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetNextFlightResults")
    @ResponseWrapper(localName = "GetNextFlightResultsResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetNextFlightResultsResponse")
    public wsimport.lib.epower.GetNextFlightResultsResponse.OTAAirLowFareSearchRS getNextFlightResults(
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaAirLowFareSearchRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.SearchFlightCalendarResponse.OTAAirLowFareSearchRS
     */
    @WebMethod(operationName = "SearchFlightCalendar", action = "http://epowerv5.amadeus.com.tr/WS/SearchFlightCalendar")
    @WebResult(name = "OTA_AirLowFareSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchFlightCalendar", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlightCalendar")
    @ResponseWrapper(localName = "SearchFlightCalendarResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlightCalendarResponse")
    public wsimport.lib.epower.SearchFlightCalendarResponse.OTAAirLowFareSearchRS searchFlightCalendar(
        @WebParam(name = "OTA_AirLowFareSearchRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.SearchFlightCalendar.OTAAirLowFareSearchRQ otaAirLowFareSearchRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaAirCheckETicketRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAAirCheckETicketRS
     */
    @WebMethod(operationName = "CheckETicket", action = "http://epowerv5.amadeus.com.tr/WS/CheckETicket")
    @WebResult(name = "OTA_AirCheckETicketRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "CheckETicket", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CheckETicket")
    @ResponseWrapper(localName = "CheckETicketResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CheckETicketResponse")
    public OTAAirCheckETicketRS checkETicket(
        @WebParam(name = "OTA_AirCheckETicketRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAAirCheckETicketRQ otaAirCheckETicketRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaAirRulesRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAAirRulesRS
     */
    @WebMethod(operationName = "GetFlightRules", action = "http://epowerv5.amadeus.com.tr/WS/GetFlightRules")
    @WebResult(name = "OTA_AirRulesRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetFlightRules", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetFlightRules")
    @ResponseWrapper(localName = "GetFlightRulesResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetFlightRulesResponse")
    public OTAAirRulesRS getFlightRules(
        @WebParam(name = "OTA_AirRulesRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAAirRulesRQ otaAirRulesRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaAirBookRQ
     * @return
     *     returns wsimport.lib.epower.BookFlightResponse.OTAAirBookRS
     */
    @WebMethod(operationName = "BookFlight", action = "http://epowerv5.amadeus.com.tr/WS/BookFlight")
    @WebResult(name = "OTA_AirBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "BookFlight", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookFlight")
    @ResponseWrapper(localName = "BookFlightResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookFlightResponse")
    public wsimport.lib.epower.BookFlightResponse.OTAAirBookRS bookFlight(
        @WebParam(name = "OTA_AirBookRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.BookFlight.OTAAirBookRQ otaAirBookRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaAirBookRQ
     * @return
     *     returns wsimport.lib.epower.BookFlightWithRecommendationResponse.OTAAirBookRS
     */
    @WebMethod(operationName = "BookFlightWithRecommendation", action = "http://epowerv5.amadeus.com.tr/WS/BookFlightWithRecommendation")
    @WebResult(name = "OTA_AirBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "BookFlightWithRecommendation", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookFlightWithRecommendation")
    @ResponseWrapper(localName = "BookFlightWithRecommendationResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookFlightWithRecommendationResponse")
    public wsimport.lib.epower.BookFlightWithRecommendationResponse.OTAAirBookRS bookFlightWithRecommendation(
        @WebParam(name = "OTA_AirBookRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.BookFlightWithRecommendation.OTAAirBookRQ otaAirBookRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaAirBookRQ
     * @return
     *     returns wsimport.lib.epower.CreateTicketResponse.OTAAirBookRS
     */
    @WebMethod(operationName = "CreateTicket", action = "http://epowerv5.amadeus.com.tr/WS/CreateTicket")
    @WebResult(name = "OTA_AirBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "CreateTicket", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CreateTicket")
    @ResponseWrapper(localName = "CreateTicketResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.CreateTicketResponse")
    public wsimport.lib.epower.CreateTicketResponse.OTAAirBookRS createTicket(
        @WebParam(name = "OTA_AirBookRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.CreateTicket.OTAAirBookRQ otaAirBookRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaReadRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetPNRResponse.OTAAirBookRS
     */
    @WebMethod(operationName = "GetPNR", action = "http://epowerv5.amadeus.com.tr/WS/GetPNR")
    @WebResult(name = "OTA_AirBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetPNR", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetPNR")
    @ResponseWrapper(localName = "GetPNRResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetPNRResponse")
    public wsimport.lib.epower.GetPNRResponse.OTAAirBookRS getPNR(
        @WebParam(name = "OTA_ReadRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.GetPNR.OTAReadRQ otaReadRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param parameters
     * @return
     *     returns wsimport.lib.epower.GetPNRPriceResponse
     */
    @WebMethod(operationName = "GetPNRPrice", action = "http://epowerv5.amadeus.com.tr/WS/GetPNRPrice")
    @WebResult(name = "GetPNRPriceResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetPNRPriceResponse getPNRPrice(
        @WebParam(name = "GetPNRPrice", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", partName = "parameters")
        GetPNRPrice parameters,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param editPNRRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.EditPNRResponse.EditPnrRS
     */
    @WebMethod(operationName = "EditPNR", action = "http://epowerv5.amadeus.com.tr/WS/EditPNR")
    @WebResult(name = "EditPnrRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "EditPNR", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.EditPNR")
    @ResponseWrapper(localName = "EditPNRResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.EditPNRResponse")
    public wsimport.lib.epower.EditPNRResponse.EditPnrRS editPNR(
        @WebParam(name = "EditPNRRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.EditPNR.EditPNRRQ editPNRRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param pnrNo
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetLastTicketingDateResponse.LastTicketingDateRS
     */
    @WebMethod(operationName = "GetLastTicketingDate", action = "http://epowerv5.amadeus.com.tr/WS/GetLastTicketingDate")
    @WebResult(name = "LastTicketingDateRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetLastTicketingDate", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetLastTicketingDate")
    @ResponseWrapper(localName = "GetLastTicketingDateResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetLastTicketingDateResponse")
    public wsimport.lib.epower.GetLastTicketingDateResponse.LastTicketingDateRS getLastTicketingDate(
        @WebParam(name = "PnrNo", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        String pnrNo,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaAirSeatMapRQ
     * @return
     *     returns wsimport.lib.epower.OTAAirSeatMapRS
     */
    @WebMethod(operationName = "GetSeatMap", action = "http://epowerv5.amadeus.com.tr/WS/GetSeatMap")
    @WebResult(name = "OTA_AirSeatMapRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetSeatMap", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetSeatMap")
    @ResponseWrapper(localName = "GetSeatMapResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetSeatMapResponse")
    public OTAAirSeatMapRS getSeatMap(
        @WebParam(name = "OTA_AirSeatMapRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAAirSeatMapRQ otaAirSeatMapRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaAirScheduleRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.SearchFlightTimeTableResponse.OTAAirScheduleRS
     */
    @WebMethod(operationName = "SearchFlightTimeTable", action = "http://epowerv5.amadeus.com.tr/WS/SearchFlightTimeTable")
    @WebResult(name = "OTA_AirScheduleRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchFlightTimeTable", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlightTimeTable")
    @ResponseWrapper(localName = "SearchFlightTimeTableResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchFlightTimeTableResponse")
    public wsimport.lib.epower.SearchFlightTimeTableResponse.OTAAirScheduleRS searchFlightTimeTable(
        @WebParam(name = "OTA_AirScheduleRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.SearchFlightTimeTable.OTAAirScheduleRQ otaAirScheduleRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param pCityCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCancelPolicyText", action = "http://epowerv5.amadeus.com.tr/WS/GetCancelPolicyText")
    @WebResult(name = "GetCancelPolicyTextResult", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetCancelPolicyText", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCancelPolicyText")
    @ResponseWrapper(localName = "GetCancelPolicyTextResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCancelPolicyTextResponse")
    public String getCancelPolicyText(
        @WebParam(name = "p_CityCode", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        String pCityCode);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaHotelSearchRQ
     * @return
     *     returns wsimport.lib.epower.OTAHotelSearchRS
     */
    @WebMethod(operationName = "SearchHotel", action = "http://epowerv5.amadeus.com.tr/WS/SearchHotel")
    @WebResult(name = "OTA_HotelSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchHotel", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchHotel")
    @ResponseWrapper(localName = "SearchHotelResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchHotelResponse")
    public OTAHotelSearchRS searchHotel(
        @WebParam(name = "OTA_HotelSearchRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.SearchHotel.OTAHotelSearchRQ otaHotelSearchRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaHotelInfoRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAHotelSearchRS
     */
    @WebMethod(operationName = "GetHotelInfo", action = "http://epowerv5.amadeus.com.tr/WS/GetHotelInfo")
    @WebResult(name = "OTA_HotelSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetHotelInfo", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelInfo")
    @ResponseWrapper(localName = "GetHotelInfoResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelInfoResponse")
    public OTAHotelSearchRS getHotelInfo(
        @WebParam(name = "OTA_HotelInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAHotelInfoRQ otaHotelInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaHotelAvailRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.SearchHotelRoomsResponse.OTAHotelAvailRS
     */
    @WebMethod(operationName = "SearchHotelRooms", action = "http://epowerv5.amadeus.com.tr/WS/SearchHotelRooms")
    @WebResult(name = "OTA_HotelAvailRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchHotelRooms", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchHotelRooms")
    @ResponseWrapper(localName = "SearchHotelRoomsResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchHotelRoomsResponse")
    public wsimport.lib.epower.SearchHotelRoomsResponse.OTAHotelAvailRS searchHotelRooms(
        @WebParam(name = "OTA_HotelAvailRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAHotelAvailRQ otaHotelAvailRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaHotelRoomRuleRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetHotelRoomRulesResponse.OTAHotelAvailRS
     */
    @WebMethod(operationName = "GetHotelRoomRules", action = "http://epowerv5.amadeus.com.tr/WS/GetHotelRoomRules")
    @WebResult(name = "OTA_HotelAvailRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetHotelRoomRules", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelRoomRules")
    @ResponseWrapper(localName = "GetHotelRoomRulesResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelRoomRulesResponse")
    public wsimport.lib.epower.GetHotelRoomRulesResponse.OTAHotelAvailRS getHotelRoomRules(
        @WebParam(name = "OTA_HotelRoomRuleRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAHotelRoomRuleRQ otaHotelRoomRuleRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaHotelResRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAHotelResRS
     */
    @WebMethod(operationName = "BookHotel", action = "http://epowerv5.amadeus.com.tr/WS/BookHotel")
    @WebResult(name = "OTA_HotelResRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "BookHotel", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookHotel")
    @ResponseWrapper(localName = "BookHotelResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookHotelResponse")
    public OTAHotelResRS bookHotel(
        @WebParam(name = "OTA_HotelResRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAHotelResRQ otaHotelResRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaReadRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAHotelResRS
     */
    @WebMethod(operationName = "GetHotelPNR", action = "http://epowerv5.amadeus.com.tr/WS/GetHotelPNR")
    @WebResult(name = "OTA_HotelResRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetHotelPNR", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelPNR")
    @ResponseWrapper(localName = "GetHotelPNRResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetHotelPNRResponse")
    public OTAHotelResRS getHotelPNR(
        @WebParam(name = "OTA_ReadRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.GetHotelPNR.OTAReadRQ otaReadRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaVehAvailRateRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAVehAvailRateRS
     */
    @WebMethod(operationName = "SearchCar", action = "http://epowerv5.amadeus.com.tr/WS/SearchCar")
    @WebResult(name = "OTA_VehAvailRateRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchCar", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchCar")
    @ResponseWrapper(localName = "SearchCarResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchCarResponse")
    public OTAVehAvailRateRS searchCar(
        @WebParam(name = "OTA_VehAvailRateRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAVehAvailRateRQ otaVehAvailRateRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaVehAvailVendorRQ
     * @return
     *     returns wsimport.lib.epower.OTAVehAvailRateRS
     */
    @WebMethod(operationName = "SearchCarVendor", action = "http://epowerv5.amadeus.com.tr/WS/SearchCarVendor")
    @WebResult(name = "OTA_VehAvailRateRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchCarVendor", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchCarVendor")
    @ResponseWrapper(localName = "SearchCarVendorResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchCarVendorResponse")
    public OTAVehAvailRateRS searchCarVendor(
        @WebParam(name = "OTA_VehAvailVendorRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAVehAvailVendorRQ otaVehAvailVendorRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaVehLocSearchRQ
     * @return
     *     returns wsimport.lib.epower.OTAVehLocSearchRS
     */
    @WebMethod(operationName = "GetCarCompanyLocations", action = "http://epowerv5.amadeus.com.tr/WS/GetCarCompanyLocations")
    @WebResult(name = "OTA_VehLocSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetCarCompanyLocations", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarCompanyLocations")
    @ResponseWrapper(localName = "GetCarCompanyLocationsResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarCompanyLocationsResponse")
    public OTAVehLocSearchRS getCarCompanyLocations(
        @WebParam(name = "OTA_VehLocSearchRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAVehLocSearchRQ otaVehLocSearchRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaVehRateRuleRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAVehRateRuleRS
     */
    @WebMethod(operationName = "GetCarRules", action = "http://epowerv5.amadeus.com.tr/WS/GetCarRules")
    @WebResult(name = "OTA_VehRateRuleRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetCarRules", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarRules")
    @ResponseWrapper(localName = "GetCarRulesResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarRulesResponse")
    public OTAVehRateRuleRS getCarRules(
        @WebParam(name = "OTA_VehRateRuleRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAVehRateRuleRQ otaVehRateRuleRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaVehResRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAVehResRS
     */
    @WebMethod(operationName = "BookCar", action = "http://epowerv5.amadeus.com.tr/WS/BookCar")
    @WebResult(name = "OTA_VehResRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "BookCar", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookCar")
    @ResponseWrapper(localName = "BookCarResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookCarResponse")
    public OTAVehResRS bookCar(
        @WebParam(name = "OTA_VehResRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAVehResRQ otaVehResRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaReadRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAVehResRS
     */
    @WebMethod(operationName = "GetCarPNR", action = "http://epowerv5.amadeus.com.tr/WS/GetCarPNR")
    @WebResult(name = "OTA_VehResRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetCarPNR", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarPNR")
    @ResponseWrapper(localName = "GetCarPNRResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetCarPNRResponse")
    public OTAVehResRS getCarPNR(
        @WebParam(name = "OTA_ReadRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.GetCarPNR.OTAReadRQ otaReadRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param otaInsurancePlanSearchRQ
     * @return
     *     returns wsimport.lib.epower.OTAInsurancePlanSearchRS
     */
    @WebMethod(operationName = "SearchInsurancePlans", action = "http://epowerv5.amadeus.com.tr/WS/SearchInsurancePlans")
    @WebResult(name = "OTA_InsurancePlanSearchRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "SearchInsurancePlans", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchInsurancePlans")
    @ResponseWrapper(localName = "SearchInsurancePlansResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.SearchInsurancePlansResponse")
    public OTAInsurancePlanSearchRS searchInsurancePlans(
        @WebParam(name = "OTA_InsurancePlanSearchRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAInsurancePlanSearchRQ otaInsurancePlanSearchRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaInsuranceBookRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.OTAInsuranceBookRS
     */
    @WebMethod(operationName = "BookInsurance", action = "http://epowerv5.amadeus.com.tr/WS/BookInsurance")
    @WebResult(name = "OTA_InsuranceBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "BookInsurance", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookInsurance")
    @ResponseWrapper(localName = "BookInsuranceResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookInsuranceResponse")
    public OTAInsuranceBookRS bookInsurance(
        @WebParam(name = "OTA_InsuranceBookRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        OTAInsuranceBookRQ otaInsuranceBookRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param bookBasketRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.BookResponse.BookBasketRS
     */
    @WebMethod(operationName = "Book", action = "http://epowerv5.amadeus.com.tr/WS/Book")
    @WebResult(name = "BookBasketRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "Book", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.Book")
    @ResponseWrapper(localName = "BookResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.BookResponse")
    public wsimport.lib.epower.BookResponse.BookBasketRS book(
        @WebParam(name = "BookBasketRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.Book.BookBasketRQ bookBasketRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param otaReadRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetBasketPNRResponse.OTAAirBookRS
     */
    @WebMethod(operationName = "GetBasketPNR", action = "http://epowerv5.amadeus.com.tr/WS/GetBasketPNR")
    @WebResult(name = "OTA_AirBookRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetBasketPNR", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetBasketPNR")
    @ResponseWrapper(localName = "GetBasketPNRResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetBasketPNRResponse")
    public wsimport.lib.epower.GetBasketPNRResponse.OTAAirBookRS getBasketPNR(
        @WebParam(name = "OTA_ReadRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.GetBasketPNR.OTAReadRQ otaReadRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param amadeusAPICommandRQ
     * @return
     *     returns wsimport.lib.epower.ExecuteCommandResponse.AmadeusAPICommandRS
     */
    @WebMethod(operationName = "ExecuteCommand", action = "http://epowerv5.amadeus.com.tr/WS/ExecuteCommand")
    @WebResult(name = "AmadeusAPICommandRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "ExecuteCommand", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.ExecuteCommand")
    @ResponseWrapper(localName = "ExecuteCommandResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.ExecuteCommandResponse")
    public wsimport.lib.epower.ExecuteCommandResponse.AmadeusAPICommandRS executeCommand(
        @WebParam(name = "AmadeusAPICommandRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.ExecuteCommand.AmadeusAPICommandRQ amadeusAPICommandRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param getUserRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.GetUserRS
     */
    @WebMethod(operationName = "GetUser", action = "http://epowerv5.amadeus.com.tr/WS/GetUser")
    @WebResult(name = "GetUserRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetUser", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetUser")
    @ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetUserResponse")
    public GetUserRS getUser(
        @WebParam(name = "GetUserRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.GetUser.GetUserRQ getUserRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param userOperationsRQ
     * @return
     *     returns wsimport.lib.epower.GetUserRS
     */
    @WebMethod(operationName = "RegisterUser", action = "http://epowerv5.amadeus.com.tr/WS/RegisterUser")
    @WebResult(name = "GetUserRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "RegisterUser", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.RegisterUser")
    @ResponseWrapper(localName = "RegisterUserResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.RegisterUserResponse")
    public GetUserRS registerUser(
        @WebParam(name = "UserOperationsRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.RegisterUser.UserOperationsRQ userOperationsRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param authenticationSoapHeader
     * @param userOperationsRQ
     * @return
     *     returns wsimport.lib.epower.GetUserRS
     */
    @WebMethod(operationName = "UpdateUser", action = "http://epowerv5.amadeus.com.tr/WS/UpdateUser")
    @WebResult(name = "GetUserRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.UpdateUserResponse")
    public GetUserRS updateUser(
        @WebParam(name = "UserOperationsRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        wsimport.lib.epower.UpdateUser.UserOperationsRQ userOperationsRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param apisRulesRQ
     * @param authenticationSoapHeader
     * @return
     *     returns wsimport.lib.epower.APISRulesRS
     */
    @WebMethod(operationName = "GetAPISRules", action = "http://epowerv5.amadeus.com.tr/WS/GetAPISRules")
    @WebResult(name = "APISRulesRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetAPISRules", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetAPISRules")
    @ResponseWrapper(localName = "GetAPISRulesResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetAPISRulesResponse")
    public APISRulesRS getAPISRules(
        @WebParam(name = "APISRulesRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        APISRulesRQ apisRulesRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

    /**
     * 
     * @param fareFamilyInfoRQ
     * @param authenticationSoapHeader
     
     * @return
     * returns wsimport.lib.epower.FareFamilyInfoRS
     */
    @WebMethod(operationName = "GetFlightFareFamilies", action = "http://epowerv5.amadeus.com.tr/WS/GetFlightFareFamilies")
    @WebResult(name = "FareFamilyInfoRS", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
    @RequestWrapper(localName = "GetFlightFareFamilies", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetFlightFareFamilies")
    @ResponseWrapper(localName = "GetFlightFareFamiliesResponse", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", className = "wsimport.lib.epower.GetFlightFareFamiliesResponse")
    public FareFamilyInfoRS getFlightFareFamilies(
        @WebParam(name = "FareFamilyInfoRQ", targetNamespace = "http://epowerv5.amadeus.com.tr/WS")
        FareFamilyInfoRQ fareFamilyInfoRQ,
        @WebParam(name = "AuthenticationSoapHeader", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", header = true, partName = "AuthenticationSoapHeader")
        AuthenticationSoapHeader authenticationSoapHeader);

}
