
package wsimport.lib.epower;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EpowerService", targetNamespace = "http://epowerv5.amadeus.com.tr/WS", wsdlLocation = "https://staging-ws.epower.amadeus.com/wsvaneng/EpowerService.asmx?WSDL")
public class EpowerService extends Service {

    private final static URL EPOWERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EPOWERSERVICE_EXCEPTION;
    private final static QName EPOWERSERVICE_QNAME = new QName("http://epowerv5.amadeus.com.tr/WS", "EpowerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://staging-ws.epower.amadeus.com/wsvaneng/EpowerService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPOWERSERVICE_WSDL_LOCATION = url;
        EPOWERSERVICE_EXCEPTION = e;
    }

    public EpowerService() {
        super(__getWsdlLocation(), EPOWERSERVICE_QNAME);
    }

    public EpowerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPOWERSERVICE_QNAME, features);
    }

    public EpowerService(URL wsdlLocation) {
        super(wsdlLocation, EPOWERSERVICE_QNAME);
    }

    public EpowerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPOWERSERVICE_QNAME, features);
    }

    public EpowerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpowerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EpowerServiceSoap
     */
    @WebEndpoint(name = "EpowerServiceSoap")
    public EpowerServiceSoap getEpowerServiceSoap() {
        return super.getPort(new QName("http://epowerv5.amadeus.com.tr/WS", "EpowerServiceSoap"), EpowerServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpowerServiceSoap
     */
    @WebEndpoint(name = "EpowerServiceSoap")
    public EpowerServiceSoap getEpowerServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://epowerv5.amadeus.com.tr/WS", "EpowerServiceSoap"), EpowerServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPOWERSERVICE_EXCEPTION!= null) {
            throw EPOWERSERVICE_EXCEPTION;
        }
        return EPOWERSERVICE_WSDL_LOCATION;
    }

}
