
package wsimport.lib.amadeus.wstransferownership;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process Transfer Ownership Messages Request.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsTransferOwnership", targetNamespace = "http://traveltalk.com/wsTransferOwnership", wsdlLocation = "http://www.tripxml.com/TripXML/wsTransferOwnership.asmx?WSDL")
public class WsTransferOwnership
    extends Service
{

    private final static URL WSTRANSFEROWNERSHIP_WSDL_LOCATION;
    private final static WebServiceException WSTRANSFEROWNERSHIP_EXCEPTION;
    private final static QName WSTRANSFEROWNERSHIP_QNAME = new QName("http://traveltalk.com/wsTransferOwnership", "wsTransferOwnership");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.tripxml.com/TripXML/wsTransferOwnership.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTRANSFEROWNERSHIP_WSDL_LOCATION = url;
        WSTRANSFEROWNERSHIP_EXCEPTION = e;
    }

    public WsTransferOwnership() {
        super(__getWsdlLocation(), WSTRANSFEROWNERSHIP_QNAME);
    }

    public WsTransferOwnership(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTRANSFEROWNERSHIP_QNAME, features);
    }

    public WsTransferOwnership(URL wsdlLocation) {
        super(wsdlLocation, WSTRANSFEROWNERSHIP_QNAME);
    }

    public WsTransferOwnership(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTRANSFEROWNERSHIP_QNAME, features);
    }

    public WsTransferOwnership(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTransferOwnership(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsTransferOwnershipSoap
     */
    @WebEndpoint(name = "wsTransferOwnershipSoap")
    public WsTransferOwnershipSoap getWsTransferOwnershipSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsTransferOwnership", "wsTransferOwnershipSoap"), WsTransferOwnershipSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTransferOwnershipSoap
     */
    @WebEndpoint(name = "wsTransferOwnershipSoap")
    public WsTransferOwnershipSoap getWsTransferOwnershipSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsTransferOwnership", "wsTransferOwnershipSoap"), WsTransferOwnershipSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTRANSFEROWNERSHIP_EXCEPTION!= null) {
            throw WSTRANSFEROWNERSHIP_EXCEPTION;
        }
        return WSTRANSFEROWNERSHIP_WSDL_LOCATION;
    }

}
