
package wsimport.lib.axamansard;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "axamdemoSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AxamdemoSoap {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(action = "http://tempuri.org/getToken")
    @WebResult(name = "getTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getToken", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetToken")
    @ResponseWrapper(localName = "getTokenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTokenResponse")
    public Result getToken(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param motor
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "Save3rdPartyPolicy", action = "http://tempuri.org/Save3rdPartyPolicy")
    @WebResult(name = "Save3rdPartyPolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Save3rdPartyPolicy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Save3RdPartyPolicy")
    @ResponseWrapper(localName = "Save3rdPartyPolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Save3RdPartyPolicyResponse")
    public Result save3RdPartyPolicy(
        @WebParam(name = "Motor", targetNamespace = "http://tempuri.org/")
        MotorObject motor,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param travel
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "SaveTravelPolicy", action = "http://tempuri.org/SaveTravelPolicy")
    @WebResult(name = "SaveTravelPolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveTravelPolicy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveTravelPolicy")
    @ResponseWrapper(localName = "SaveTravelPolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveTravelPolicyResponse")
    public Result saveTravelPolicy(
        @WebParam(name = "Travel", targetNamespace = "http://tempuri.org/")
        TravelObject travel,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param trans
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "Book3rdPartyMotor", action = "http://tempuri.org/Book3rdPartyMotor")
    @WebResult(name = "Book3rdPartyMotorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Book3rdPartyMotor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Book3RdPartyMotor")
    @ResponseWrapper(localName = "Book3rdPartyMotorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Book3RdPartyMotorResponse")
    public Result book3RdPartyMotor(
        @WebParam(name = "Trans", targetNamespace = "http://tempuri.org/")
        String trans,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param trans
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "BookComprehensiveMotor", action = "http://tempuri.org/BookComprehensiveMotor")
    @WebResult(name = "BookComprehensiveMotorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BookComprehensiveMotor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookComprehensiveMotor")
    @ResponseWrapper(localName = "BookComprehensiveMotorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookComprehensiveMotorResponse")
    public Result bookComprehensiveMotor(
        @WebParam(name = "Trans", targetNamespace = "http://tempuri.org/")
        String trans,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param trans
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "BookTravelPolicy", action = "http://tempuri.org/BookTravelPolicy")
    @WebResult(name = "BookTravelPolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BookTravelPolicy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookTravelPolicy")
    @ResponseWrapper(localName = "BookTravelPolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookTravelPolicyResponse")
    public Result bookTravelPolicy(
        @WebParam(name = "Trans", targetNamespace = "http://tempuri.org/")
        String trans,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVehicleMakes", action = "http://tempuri.org/GetVehicleMakes")
    @WebResult(name = "GetVehicleMakesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVehicleMakes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleMakes")
    @ResponseWrapper(localName = "GetVehicleMakesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleMakesResponse")
    public String getVehicleMakes(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetThirdPartyCategories", action = "http://tempuri.org/GetThirdPartyCategories")
    @WebResult(name = "GetThirdPartyCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetThirdPartyCategories", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetThirdPartyCategories")
    @ResponseWrapper(localName = "GetThirdPartyCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetThirdPartyCategoriesResponse")
    public String getThirdPartyCategories(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param categoryID
     * @param token
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetThridPartyPremium", action = "http://tempuri.org/GetThridPartyPremium")
    @WebResult(name = "GetThridPartyPremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetThridPartyPremium", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetThridPartyPremium")
    @ResponseWrapper(localName = "GetThridPartyPremiumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetThridPartyPremiumResponse")
    public BigDecimal getThridPartyPremium(
        @WebParam(name = "CategoryID", targetNamespace = "http://tempuri.org/")
        int categoryID,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param motor
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "SaveComprehensiveMotor", action = "http://tempuri.org/SaveComprehensiveMotor")
    @WebResult(name = "SaveComprehensiveMotorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveComprehensiveMotor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveComprehensiveMotor")
    @ResponseWrapper(localName = "SaveComprehensiveMotorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveComprehensiveMotorResponse")
    public Result saveComprehensiveMotor(
        @WebParam(name = "Motor", targetNamespace = "http://tempuri.org/")
        MotorObject motor,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param trans
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "BookMIP", action = "http://tempuri.org/BookMIP")
    @WebResult(name = "BookMIPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BookMIP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookMIP")
    @ResponseWrapper(localName = "BookMIPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookMIPResponse")
    public Result bookMIP(
        @WebParam(name = "Trans", targetNamespace = "http://tempuri.org/")
        String trans,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param life
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "SaveMIP", action = "http://tempuri.org/SaveMIP")
    @WebResult(name = "SaveMIPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveMIP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveMIP")
    @ResponseWrapper(localName = "SaveMIPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveMIPResponse")
    public Result saveMIP(
        @WebParam(name = "Life", targetNamespace = "http://tempuri.org/")
        LifeObject life,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMIPQuotes", action = "http://tempuri.org/GetMIPQuotes")
    @WebResult(name = "GetMIPQuotesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMIPQuotes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMIPQuotes")
    @ResponseWrapper(localName = "GetMIPQuotesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMIPQuotesResponse")
    public String getMIPQuotes(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTitles", action = "http://tempuri.org/GetTitles")
    @WebResult(name = "GetTitlesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTitles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTitles")
    @ResponseWrapper(localName = "GetTitlesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTitlesResponse")
    public String getTitles(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGenders", action = "http://tempuri.org/GetGenders")
    @WebResult(name = "GetGendersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGenders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGenders")
    @ResponseWrapper(localName = "GetGendersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGendersResponse")
    public String getGenders(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBeneficiaryRelationships", action = "http://tempuri.org/GetBeneficiaryRelationships")
    @WebResult(name = "GetBeneficiaryRelationshipsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBeneficiaryRelationships", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBeneficiaryRelationships")
    @ResponseWrapper(localName = "GetBeneficiaryRelationshipsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBeneficiaryRelationshipsResponse")
    public String getBeneficiaryRelationships(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBeneficiaryType", action = "http://tempuri.org/GetBeneficiaryType")
    @WebResult(name = "GetBeneficiaryTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBeneficiaryType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBeneficiaryType")
    @ResponseWrapper(localName = "GetBeneficiaryTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBeneficiaryTypeResponse")
    public String getBeneficiaryType(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMaritalStatus", action = "http://tempuri.org/GetMaritalStatus")
    @WebResult(name = "GetMaritalStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMaritalStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMaritalStatus")
    @ResponseWrapper(localName = "GetMaritalStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMaritalStatusResponse")
    public String getMaritalStatus(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReligion", action = "http://tempuri.org/GetReligion")
    @WebResult(name = "GetReligionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReligion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReligion")
    @ResponseWrapper(localName = "GetReligionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReligionResponse")
    public String getReligion(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOccupations", action = "http://tempuri.org/GetOccupations")
    @WebResult(name = "GetOccupationsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccupations", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOccupations")
    @ResponseWrapper(localName = "GetOccupationsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOccupationsResponse")
    public String getOccupations(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStates", action = "http://tempuri.org/GetStates")
    @WebResult(name = "GetStatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStates", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStates")
    @ResponseWrapper(localName = "GetStatesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatesResponse")
    public String getStates(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param stateId
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLGA", action = "http://tempuri.org/GetLGA")
    @WebResult(name = "GetLGAResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLGA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLGA")
    @ResponseWrapper(localName = "GetLGAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLGAResponse")
    public String getLGA(
        @WebParam(name = "StateId", targetNamespace = "http://tempuri.org/")
        int stateId,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param custNo
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "GetCustomerDetails", action = "http://tempuri.org/GetCustomerDetails")
    @WebResult(name = "GetCustomerDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetails")
    @ResponseWrapper(localName = "GetCustomerDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailsResponse")
    public Result getCustomerDetails(
        @WebParam(name = "CustNo", targetNamespace = "http://tempuri.org/")
        String custNo,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param carType
     * @param policyCode
     * @param token
     * @param carValue
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetComprehensiveMotorPremium", action = "http://tempuri.org/GetComprehensiveMotorPremium")
    @WebResult(name = "GetComprehensiveMotorPremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetComprehensiveMotorPremium", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetComprehensiveMotorPremium")
    @ResponseWrapper(localName = "GetComprehensiveMotorPremiumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetComprehensiveMotorPremiumResponse")
    public String getComprehensiveMotorPremium(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "PolicyCode", targetNamespace = "http://tempuri.org/")
        String policyCode,
        @WebParam(name = "CarType", targetNamespace = "http://tempuri.org/")
        int carType,
        @WebParam(name = "CarValue", targetNamespace = "http://tempuri.org/")
        BigDecimal carValue);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMTInsuranceTypes", action = "http://tempuri.org/GetMTInsuranceTypes")
    @WebResult(name = "GetMTInsuranceTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMTInsuranceTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTInsuranceTypes")
    @ResponseWrapper(localName = "GetMTInsuranceTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTInsuranceTypesResponse")
    public String getMTInsuranceTypes();

    /**
     * 
     * @param insuranceType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMTPlan", action = "http://tempuri.org/GetMTPlan")
    @WebResult(name = "GetMTPlanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMTPlan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTPlan")
    @ResponseWrapper(localName = "GetMTPlanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTPlanResponse")
    public String getMTPlan(
        @WebParam(name = "InsuranceType", targetNamespace = "http://tempuri.org/")
        int insuranceType);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMTPolicyTypes", action = "http://tempuri.org/GetMTPolicyTypes")
    @WebResult(name = "GetMTPolicyTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMTPolicyTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTPolicyTypes")
    @ResponseWrapper(localName = "GetMTPolicyTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTPolicyTypesResponse")
    public String getMTPolicyTypes();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTripPurposes", action = "http://tempuri.org/GetTripPurposes")
    @WebResult(name = "GetTripPurposesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTripPurposes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTripPurposes")
    @ResponseWrapper(localName = "GetTripPurposesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTripPurposesResponse")
    public String getTripPurposes();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCountries", action = "http://tempuri.org/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCountriesResponse")
    public String getCountries();

    /**
     * 
     * @param duration
     * @param password
     * @param policyType
     * @param ages
     * @param noOfPersons
     * @param planCode
     * @param username
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "GetMTCost", action = "http://tempuri.org/GetMTCost")
    @WebResult(name = "GetMTCostResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMTCost", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTCost")
    @ResponseWrapper(localName = "GetMTCostResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMTCostResponse")
    public Result getMTCost(
        @WebParam(name = "Ages", targetNamespace = "http://tempuri.org/")
        ArrayOfInt ages,
        @WebParam(name = "PolicyType", targetNamespace = "http://tempuri.org/")
        int policyType,
        @WebParam(name = "PlanCode", targetNamespace = "http://tempuri.org/")
        String planCode,
        @WebParam(name = "NoOfPersons", targetNamespace = "http://tempuri.org/")
        int noOfPersons,
        @WebParam(name = "Duration", targetNamespace = "http://tempuri.org/")
        int duration,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param planCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDestinations", action = "http://tempuri.org/GetDestinations")
    @WebResult(name = "GetDestinationsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDestinations", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDestinations")
    @ResponseWrapper(localName = "GetDestinationsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDestinationsResponse")
    public String getDestinations(
        @WebParam(name = "PlanCode", targetNamespace = "http://tempuri.org/")
        String planCode);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBanks", action = "http://tempuri.org/GetBanks")
    @WebResult(name = "GetBanksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBanks", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBanks")
    @ResponseWrapper(localName = "GetBanksResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBanksResponse")
    public String getBanks();

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVehicleCatetgory", action = "http://tempuri.org/GetVehicleCatetgory")
    @WebResult(name = "GetVehicleCatetgoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVehicleCatetgory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleCatetgory")
    @ResponseWrapper(localName = "GetVehicleCatetgoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleCatetgoryResponse")
    public String getVehicleCatetgory(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIdentificationTypes", action = "http://tempuri.org/GetIdentificationTypes")
    @WebResult(name = "GetIdentificationTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentificationTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentificationTypes")
    @ResponseWrapper(localName = "GetIdentificationTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentificationTypesResponse")
    public String getIdentificationTypes(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param stateID
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInspectionCities", action = "http://tempuri.org/GetInspectionCities")
    @WebResult(name = "GetInspectionCitiesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInspectionCities", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInspectionCities")
    @ResponseWrapper(localName = "GetInspectionCitiesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInspectionCitiesResponse")
    public String getInspectionCities(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "StateID", targetNamespace = "http://tempuri.org/")
        int stateID);

    /**
     * 
     * @param cityID
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInspectionAddress", action = "http://tempuri.org/GetInspectionAddress")
    @WebResult(name = "GetInspectionAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInspectionAddress", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInspectionAddress")
    @ResponseWrapper(localName = "GetInspectionAddressResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInspectionAddressResponse")
    public String getInspectionAddress(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "CityID", targetNamespace = "http://tempuri.org/")
        int cityID);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRegistrationPlaces", action = "http://tempuri.org/GetRegistrationPlaces")
    @WebResult(name = "GetRegistrationPlacesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegistrationPlaces", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationPlaces")
    @ResponseWrapper(localName = "GetRegistrationPlacesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationPlacesResponse")
    public String getRegistrationPlaces(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param transactionReference
     * @param token
     * @return
     *     returns org.tempuri.Result
     */
    @WebMethod(operationName = "GetSavedPolicyData", action = "http://tempuri.org/GetSavedPolicyData")
    @WebResult(name = "GetSavedPolicyDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSavedPolicyData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSavedPolicyData")
    @ResponseWrapper(localName = "GetSavedPolicyDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSavedPolicyDataResponse")
    public Result getSavedPolicyData(
        @WebParam(name = "TransactionReference", targetNamespace = "http://tempuri.org/")
        String transactionReference,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

}
