
package wsimport.lib.amadeus.pnr.read;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsPNRReadSoap", targetNamespace = "http://traveltalk.com/wsPNRRead")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsPNRReadSoap {


    /**
     * Process PNR Read Messages Request.
     * 
     * @param otaReadRQ
     * @return
     *     returns com.traveltalk.wspnrread.OTATravelItineraryRS
     */
    @WebMethod(action = "http://traveltalk.com/wsPNRRead/wmPNRRead")
    @WebResult(name = "OTA_TravelItineraryRS", targetNamespace = "http://traveltalk.com/wsPNRRead")
    @RequestWrapper(localName = "wmPNRRead", targetNamespace = "http://traveltalk.com/wsPNRRead", className = "com.traveltalk.wspnrread.WmPNRRead")
    @ResponseWrapper(localName = "wmPNRReadResponse", targetNamespace = "http://traveltalk.com/wsPNRRead", className = "com.traveltalk.wspnrread.WmPNRReadResponse")
    public OTATravelItineraryRS wmPNRRead(
            @WebParam(name = "OTA_ReadRQ", targetNamespace = "http://traveltalk.com/wsPNRRead")
                    OTAReadRQ otaReadRQ);

    /**
     * Process PNR Read Xml Messages Request.
     * 
     * @param xmlRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://traveltalk.com/wsPNRRead/wmPNRReadXml")
    @WebResult(name = "wmPNRReadXmlResult", targetNamespace = "http://traveltalk.com/wsPNRRead")
    @RequestWrapper(localName = "wmPNRReadXml", targetNamespace = "http://traveltalk.com/wsPNRRead", className = "com.traveltalk.wspnrread.WmPNRReadXml")
    @ResponseWrapper(localName = "wmPNRReadXmlResponse", targetNamespace = "http://traveltalk.com/wsPNRRead", className = "com.traveltalk.wspnrread.WmPNRReadXmlResponse")
    public String wmPNRReadXml(
            @WebParam(name = "xmlRequest", targetNamespace = "http://traveltalk.com/wsPNRRead")
                    String xmlRequest);

}
