
package wsimport.lib.amadeus.pnr.read;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A TripXML Web Service to Process PNR Read Request - version 03.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsPNRRead", targetNamespace = "http://traveltalk.com/wsPNRRead", wsdlLocation = "http://amadeusws.tripxml.com/TripXML/wsPNRRead_v03.asmx?WSDL")
public class WsPNRRead
    extends Service
{

    private final static URL WSPNRREAD_WSDL_LOCATION;
    private final static WebServiceException WSPNRREAD_EXCEPTION;
    private final static QName WSPNRREAD_QNAME = new QName("http://traveltalk.com/wsPNRRead", "wsPNRRead");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://amadeusws.tripxml.com/TripXML/wsPNRRead_v03.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPNRREAD_WSDL_LOCATION = url;
        WSPNRREAD_EXCEPTION = e;
    }

    public WsPNRRead() {
        super(__getWsdlLocation(), WSPNRREAD_QNAME);
    }

    public WsPNRRead(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPNRREAD_QNAME, features);
    }

    public WsPNRRead(URL wsdlLocation) {
        super(wsdlLocation, WSPNRREAD_QNAME);
    }

    public WsPNRRead(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPNRREAD_QNAME, features);
    }

    public WsPNRRead(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPNRRead(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsPNRReadSoap
     */
    @WebEndpoint(name = "wsPNRReadSoap")
    public WsPNRReadSoap getWsPNRReadSoap() {
        return super.getPort(new QName("http://traveltalk.com/wsPNRRead", "wsPNRReadSoap"), WsPNRReadSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPNRReadSoap
     */
    @WebEndpoint(name = "wsPNRReadSoap")
    public WsPNRReadSoap getWsPNRReadSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://traveltalk.com/wsPNRRead", "wsPNRReadSoap"), WsPNRReadSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPNRREAD_EXCEPTION!= null) {
            throw WSPNRREAD_EXCEPTION;
        }
        return WSPNRREAD_WSDL_LOCATION;
    }

}
